// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMember = "member_info"

// Member mapped from table <member_info>
type Member struct {
	ID             int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Code           string `gorm:"column:code;type:varchar(16);not null;index:ix_member_info_code,priority:1;comment:用户编码" json:"code"`                                   // 用户编码
	FollowInviter  string `gorm:"column:follow_inviter;type:varchar(16);not null;index:ix_member_info_follow_inviter,priority:1;comment:关注邀请人" json:"follow_inviter"`    // 关注邀请人
	PaymentInviter string `gorm:"column:payment_inviter;type:varchar(16);not null;index:ix_member_info_payment_inviter,priority:1;comment:支付邀请人" json:"payment_inviter"` // 支付邀请人
	Openid         string `gorm:"column:openid;type:varchar(30);not null;index:ix_member_info_openid,priority:1;comment:openid" json:"openid"`                           // openid
	Unionid        string `gorm:"column:unionid;type:varchar(30);not null;index:ix_member_info_unionid,priority:1;comment:unionid" json:"unionid"`                       // unionid
	Nickname       string `gorm:"column:nickname;type:varchar(120);not null;index:ix_member_info_nickname,priority:1;comment:昵称" json:"nickname"`                        // 昵称
	Avatar         string `gorm:"column:avatar;type:varchar(255);not null;comment:头像" json:"avatar"`                                                                     // 头像
	Account        string `gorm:"column:account;type:varchar(120);not null;index:ix_member_info_account,priority:1;comment:账号" json:"account"`                           // 账号
	Password       string `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`                                                                 // 密码
	Email          string `gorm:"column:email;type:varchar(120);not null;comment:邮箱" json:"email"`                                                                       // 邮箱
	Mobile         string `gorm:"column:mobile;type:varchar(120);not null;index:ix_member_info_mobile,priority:1;comment:手机号" json:"mobile"`                             // 手机号
	Username       string `gorm:"column:username;type:varchar(120);not null;comment:用户名" json:"username"`                                                                // 用户名
	Company        string `gorm:"column:company;type:varchar(255);not null;comment:公司名" json:"company"`                                                                  // 公司名
	Province       int64  `gorm:"column:province;type:int;not null;comment:省份" json:"province"`                                                                          // 省份
	City           int64  `gorm:"column:city;type:int;not null;comment:市" json:"city"`                                                                                   // 市
	Address        string `gorm:"column:address;type:varchar(255);not null;comment:地址" json:"address"`                                                                   // 地址
	/*
		会员等级
		0: 非会员
		10: VIP会员
		11: 高级会员
		12: 钻石会员
		17: 试用会员
		18: 测试会员
		19: 内部会员
		21: 原1 VIP会员
		22: 原2 高级会员
		23: 原3 钻石会员
		24: 原4 试用会员
		25: 原5 内部会员
		26: 原6 其他会员
	*/
	Level    int64     `gorm:"column:level;type:int;not null;comment:会员等级\n0: 非会员\n10: VIP会员\n11: 高级会员\n12: 钻石会员\n17: 试用会员\n18: 测试会员\n19: 内部会员\n21: 原1 VIP会员\n22: 原2 高级会员\n23: 原3 钻石会员\n24: 原4 试用会员\n25: 原5 内部会员\n26: 原6 其他会员" json:"level"`
	Expires  time.Time `gorm:"column:expires;type:datetime;not null;default:2002-01-01 00:00:00;comment:会员到期时间" json:"expires"` // 会员到期时间
	Readable int64     `gorm:"column:readable;type:int;not null;comment:剩余数量" json:"readable"`                                  // 剩余数量
	/*
		会员状态
		0: 默认状态
		-1: 公众号取关
	*/
	Status     int64     `gorm:"column:status;type:int;not null;comment:会员状态\n0: 默认状态\n-1: 公众号取关" json:"status"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP;autoUpdateTime;comment:创建时间" json:"update_time"` // 创建时间
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;autoCreateTime;comment:更新时间" json:"create_time"` // 更新时间
	RegTyp     string    `gorm:"column:reg_typ;type:varchar(255);not null;comment:注册渠道" json:"reg_typ"`                                              // 注册渠道
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
